---
apiVersion: autoscaling/v2beta2
# Можно использовать HPA 
kind: HorizontalPodAutoscaler 
metadata:
  name: backend
  labels:
    app: backend
spec:
# кол-во реплик можно увеличить до 2
  minReplicas: 1 
# максимальное кол-во реплик
  maxReplicas: 4 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  metrics:
    — type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
# новые поды будут разворачиваться если нагрузка на CPU превышает более 75%
          averageUtilization: 75 
